export class VentaDto {
  public importe!: string;
  public fechaInicio!: string;
  public fechaFin!: string;
  public tipoDeCambio!: string;
  public account!: string;
  public currency: string = "BOL";
  public description: string = "";
  public isMultipleDebits: boolean = false;
  public uif: string | null = null;
  public isValidUif: boolean = false;
  public operationStatusId: number = 0;
  public isAch: boolean = false;
  public operationTypeId: number = 49;
  public isScheduledProcess: boolean = false;
  public type: number = 0;
  public sourceAccount!: string;
  public sourceAccountId!: string;
  public sourceCurrency: string = "BOL";
  public approvers!: any[];
  public controllers!: any[];
  public cismartApprovers!: any[];
  public targetAccountCurrency: string | null = null;
  public destinationAccount: string | null = null;
  public indicatorBuyOrSale: string = "";
  public isTicket: boolean = false;
  public numberTicket!: string | null;
  public preferentialExchange: number = 0;
  public ip!: string;
  public amount!: string;
  public amountSus!: string;
  public fundSource: string | null = "";
  public fundDestination: string | null = "";
  public sendVouchers: string | null = null;
  public isPrePreparer: boolean = false;
  public tokenCode!: string;
  public tokenName!: string;
  public bsAccount!: string;
  public dollarBuyId!: number;
  public dollarSellId!: number;
  public companyId!: number;
  public Terms!: boolean;
}
