//import { EnvironmentConfig } from '../app/models/config/environment.model';

export const environment = {
  production: false,
  envName: 'cert',
  apiBaseUrls: {
    AccountsServiceUrl: "https://CERCWM10/SiteCW/accounts/api/accounts/",
    ApproversAndControllersServiceUrl: "https://CERCWM10/SiteCW/approversandcontrollers/api/approversandcontrollers/",
    AuthorizationServiceUrl: "https://CERCWM10/SiteCwAut/authorization/api/authorization/",
    AuthUrl: "https://CERCWM10/SiteCW/JwtAuthentication/",
    NewAuthUrl: "https://CERCWM10/SiteAuthCw/JwtAuthServer/api/JwtAuthServer/",
    BalancesAndMovementsServiceUrl: "https://CERCWM10/SiteCW/balancesandmovements/api/balancesandmovements/",
    CashPaymentServiceUrl: "https://CERCWM10/SiteCW/cashPayments/api/cashPayments/",
    ClaimRequestUrl: "https://CERCWM10/SiteCW/claimRequest/api/claimRequest/",
    CreditCardsServiceUrl: "https://CERCWM10/SiteCW/creditcards/api/creditCards/",
    CreditsServiceUrl: "https://CERCWM10/SiteCW/QuotasPayments/api/QuotasPayment/",
    ExchangeRatesServiceUrl: "https://CERCWM10/SiteCW/exchangerates/api/exchangerates/",
    FavoriteTransfersServiceUrl: "https://CERCWM10/SiteCW/favoritetransfers/api/favoriteTransfers/",
    FavoritePaymentServiceUrl: "https://CERCWM10/SiteCW/favoritePayments/api/oldfavoritePayments/",
    FavoritePaymentConfigServiceUrl: "https://CERCWM10/SiteCW/favoritePaymentsConfig/api/OldFavoritePayments/",
    LimitsServiceUrl: "https://CERCWM10/SiteCW/limits/api/limits/",
    MovementsAndDepositsUrl: "https://CERCWM10/SiteCW/MovementDeposits/api/MovementDeposits/",
    MultiplePaymentServiceUrl: "https://CERCWM10/SiteCW/multiplePayments/api/oldmultiplePayments/",
    ParametersServiceUrl: "https://CERCWM10/SiteCW/parameters/api/parameters/",
    PaseUrl: "https://CERCWM10/SiteCW/PaseService/api/pase/",
    PaymentTaxCheckUrl: "https://CERCWM10/SiteCW/PaymentTaxChecks/api/TaxCheck/",
    ProvidersCheckManagementUrl: "https://CERCWM10/SiteCW/ProvidersCheckManagement/api/ManagementCheck/",
    ProvidersDepositInOtherBankCheckUrl: "https://CERCWM10/SiteCW/ProvidersDepositOtherBankCheck/api/OldDepositOtherBank/",
    ProvidersPaymentsServiceUrl: "https://CERCWM10/SiteCW/providersPayments/api/providersPayments/",
    RuatServiceUrl: "https://CERCWM10/SiteCW/ruat/api/ruat/",
    SalariesPaymentServiceUrl: "https://CERCWM10/SiteCW/salariesPayments/api/salariesPayments/",
    ServicePaymentsServiceUrl: "https://CERCWM10/SiteCW/servicepayments/api/servicePayments/",
    TransfersAbroadServiceUrl: "https://CERCWM10/SiteCW/transfersAbroad/api/transfersAbroad/",
    TransfersServiceUrl: "https://CERCWM10/SiteCW/transfers/api/transfers/",
    TicketsServiceUrl: "https://CERCWM10/SiteCW/tickets/api/tickets/",
    TokensServiceUrl: "https://CERCWM10/SiteCW/tokens/api/tokens/",
    UrlListHistorical: "https://CERCWM10/SiteCW/HistoricalAccounts/api/HistoricalAccounts/",
    PaymentAchUrl: "https://CERCWM10/SiteCW/PaymentBankAch/api/PaymentBankAch/",
    PaymentOddAchUrl: "https://CERCWM10/SiteCW/PaymentOddAch/api/OldPaymentODD/",
    VoucherElectronicUrl: "https://CERCWM10/SiteCW/ElectronicVoucher/api/ElectronicVoucher/",
    ChecksServiceUrl: "https://CERCWM10/SiteCW/checks/api/Checks/",
    TrackTransfersUrl: "https://CERCWM10/SiteCW/TrackTransfers/api/TrackTransfers/",
    ElectronicBillUrl: "https://CERCWM10/SiteCW/ElectronicBilling/api/ElectronicBilling/",
    VouchersUrl: "https://CERCWM10/SiteCW/voucheroperations/api/voucheroperations/",
    VouchersUrlV3: "https://CERCWM10/SiteCW/voucheroperationsV3/api/voucheroperationsV3/",
    VouchersByOperationUrl: "https://CERCWM10/SiteCW/VouchersByOperation/api/VouchersByOperation/",
    ModificationRequestUrl: "https://CERCWM10/SiteCW/RequestModifications/api/RequestModifications/",
    AFPUrl: "https://CERCWM10/SiteCW/AFP/api/AFP/",
    OldVouchersUrl: "https://CERCWM10/SiteCW/OldVoucherOperations/api/VoucherByTime/",
    UIFServiceUrl: "https://CERCWM10/SiteCW/UIF/api/UIF/",
    BallotOfWarrantyUrl: "https://CERCWM10/SiteCW/WarrantyBallots/api/ballotOfWarranty/",
    ElfecUrl: "https://CERCWM10/SiteCW/ElfecPayments/api/Elfec/",
    ServicePaseUrl: "https://CERCWM10/SiteCW/ServicesPasePayments/api/ServicesPase/",
    OTPUrl: "https://CERCWM10/SiteCW/OTP/api/OTP/",
    OtpIamUrl: "https://CERCWM10/SiteCW/OtpIamCw/api/OtpIamCw/",
    VouchersByBatchUrl: "https://CERCWM10/SiteCW/VouchersByBatch/api/VouchersByBatch/",
    telephoneServiceUrl: "https://CERCWM10/SiteCW/TelephoneServicesPayments/api/TelephoneServices/",
    tigoPaymentUrl: "https://CERCWM10/SiteCW/TigoPayments/api/TigoPayments/",
    NewPaseUrl: "https://CERCWM10/SiteCW/NewPasePayments/api/NewPase/",
    EventLogServiceUrl: "https://CERCWM10/SiteCW/EventLog/api/EventLog/",
    QrPaymentServiceUrl: "https://CERCWM10/SiteCW/QRPayment/api/QR/",
    NewBallotOfWarrantyUrl: "https://CERCWM10/SiteCW/NewWarrantyBallots/api/NewBallotOfWarranty/",
    SoliPaymentServiceUrl: "https://CERCWM10/SiteCW/SoliPayments/api/SoliPayments/",
    CashPaymentOnlineServiceUrl: "https://CERCWM10/SiteCW/CashPaymentsOnline/api/CashPaymentsOnline/",
    VouchersZipUrl: "https://CERCWM10/SiteCW/VouchersZip/api/VouchersZip/",
    ApiInfoEnrequecidaUrl: "https://CERCWM10/SiteCW/APIInfoEnrequecida/api/APIInfoEnrequecida/",
    RegBoQrServicesUrl: "https://CERCWM10/SiteCW/QRPayment/api/RegBackOfficeQR/",
    DBFDMonitor: "https://CERCWM10/SiteCW/DBFDMonitor/api/DBFDMonitor/",
    AffiliationUserCwUrl: "https://CERCWM10/SiteCW/OBCompanyAffiliationsV2/api/OBCompanyAffiliationsV2/",
    NewOtpUrl: "https://CERCWM10/SiteCwAut/NewOtp/api/NewOtp/",
    NewTrackTrackingUrl: "https://CERCWM10/SiteCW/NewTrckTracking/api/NewTrckTracking/",
    FxServices: "https://CERCWM10/SiteCwAut/TransfersDollars/api/",
    AuthUrlSession: "https://CERCWM10/SiteAuthCw/AuthBridge/api/AuthBridge/",
    AuthUrlLegacy: "https://CERCWM10/cw/#/",
    QrPaymentAchServiceUrl: "https://CERCWM10/SiteCW/QrPaymentAch/api/QrPaymentAch/",
    ComicionConfianza: 0.05,
    Banquero: {
      id: 1,
      name: "BCP MIAMI",
      currency: "USD",
      bicSwift: "BCPLUS33",
      country: "USA",
      accountNumber: "1150120000247"
    },
    padTokenLength: "10",
    padTokenVULength: "6",
    showMessageInitial: true,
    validateCaptcha: false,
    messageIsBlocked: "Estimado usuario usted no puede realizar la operación.",
    ClientId: "f82e450ad49e4284a613ed9a4a5deb74",
    publicKeyRecaptcha: "6LfwNqsUAAAAABOSHAAvVFUiAxdiHTJEkzllBnc7",
    MessageQR: "Estimado cliente, debido a las mejoras realizadas en la funcionalidad de QR, a partir de la fecha necesitaremos realizar el registro de algunos datos de su empresa para que puedan generar códigos y reportes de QR en línea. Favor de enviar un correo al buzón de Help Desk: bolhdspe@bcp.com.bo solicitando el formulario de registro.",
    EncryptKey: "jadOj4oPEZ0YPIBS254oMWjoCNm39tKU89TrJyqKGho=",
    ThumbPrintKey: "1234567890123456",
    isRecaptcha: true,
    validateProdem: true,
    isUif: false,
    showOriginDestinationFunds: true,
    showServicePase: [false, false, true, true, true, false, false],
    showGPI: false,
    showYPFB: true,
    showNewService: true,
    redirectionUrl: "https://cercwm10/#/login",
    redirectionMinutes: 10,
    logoutSeconds: 15,
    validateHash: true,
    isEncrypt: true,
    maxLength: 15,
    isValidateIP: true,
    validateSession: true,
    validateSesionTime: false,
    DaysQrReport: 30,
    CompaniesReporteNewQR: "22",
    StateQR: [
      { value: "P", description: "PROCESADO" },
      { value: "C", description: "NO PROCESADO" }
    ],
    isTokenVU: true,
    IsNewJwt: true,
    IsPasswordNewJwt: true,
    OBUser: "CREDINET_USER",
    OBChannel: "CWWB",
    OBPassword: "014F50A94F7A59EE4800E4F734905B4FA8AA",
    OBAppUserId: "CWWBUser18012023",
    OBPublicToken: "99C814DD-19AF-424B-B658-10629717AF67",
    OnboardingMobile: {
      GetOnboardingMobileDataUrl: "https://CERCWM10/SiteCW/OnboardingMobile/api/OnboardingMobile/GetOnboardingMobileData",
      CreateDigitalFileAndSendOTPUrl: "https://CERCWM10/SiteCW/OBCompanyAffiliationsV2/api/OBCompanyAffiliationsV2/CreateDigitalFileAndSendOTP",
      ValidateOTPDigitalFileUrl: "https://CERCWM10/SiteCW/OBCompanyAffiliationsV2/api/OBCompanyAffiliationsV2/ValidateOTPDigitalFile",
      GetRespPassiveLiveTestUrl: "https://CERCWM10/SiteCW/OBCompanyAffiliationsV2/api/OBCompanyAffiliationsV2/GetRespPassiveLiveTest",
      GetValidatePassiveLiveTestUrl: "https://CERCWM10/SiteCW/OBCompanyAffiliationsV2/api/OBCompanyAffiliationsV2/GetValidatePassiveLiveTest",
      DigitalFileReSendOTPUrl: "https://CERCWM10/SiteCW/OBCompanyAffiliationsV2/api/OBCompanyAffiliationsV2/DigitalFileReSendOTP",
      SaveFinalDataToCWAffUrl: "https://CERCWM10/SiteCW/OnboardingMobile/api/OnboardingMobile/SaveFinalDataToCWAff"
    },
    createDocSignature: true
  }
}
