
// Generated by https://quicktype.io

export class ResponseData {
  data!:    Data;
  state!:   string;
  message!: string;
  constructor(values: Object = {}) {
      Object.assign(this, values);
  }
}

export class Data {
  accountHolder!:     string;
  cic!:               string;
  status!:            string;
  statusDescription!: string;
  product!:           string;
  accountNumber!:     string;
  accountType!:       string;
  currency!:          string;
  endingBalance!:     number;
  initialBalance!:    number;
  period!:            string;
  transactions:      Transaction[] = [];
  constructor(values: Object = {}) {
      Object.assign(this, values);
  }
}

export class Transaction {
  id!:                  number;
  date!:                string;
  hour!:                string;
  hostOperationNumber!: string;
  description!:         string;
  channel!:             string;
  gloss!:               string;
  location!:            string;
  amount!:              number;
  agencyBranch!:        string;
  teti!:                string;
  valuta!:              string;
  user!:                string;
  utc!:                 string;
  TransactionType!:     string;
  destinationAccount!:  string;
  beneficiary!:         string;
  destinationBank!:     string;
  destinationGloss!:    string;
  companyNameTrade!:    string;
  companyService!:      string;
  depositorCode!:       string;
  emisorAccount!:       string;
  emisor!:              string;
  sourceBank!:          string;

  constructor(values: Object = {}) {
      Object.assign(this, values);
  }
}
